#
# Copyright 2017 Alien Labs.
#

#
# Console:
# https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions?display=list
#

# TODO(burdon): Change sub/api
service: orbital-api


provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1

  stage: dev

  environment:
    SERVICE_NAME:   ${self:service}
    VERSION:        "0.0.1"
    CONFIG_DIR:     "./config"
    DATABASE:       'dynamodb'
    AWS_USER:       "testing"
    AWS_CONFIG:     "aws-dev.yml"


plugins:
  # https://www.npmjs.com/package/serverless-domain-manager
  - "serverless-domain-manager"

  # sls info --json | jq
  # https://www.npmjs.com/package/serverless-plugin-info-json
  - "serverless-plugin-info-json"

  # Webpack
  # https://www.npmjs.com/package/serverless-webpack
  - "serverless-webpack"


custom:
  webpack: "webpack.config.js"

  customDomain:
    domainName: api.orbitaldb.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true


functions:

  status:
    handler: handler.status
    description: "Status service."
    events:
      - http:
          path: status
          method: get
          cors: true

  registry:
    handler: handler.registry
    description: "Registry GraphQL API."
    events:
      - http:
          path: registry
          method: post
          cors: true

  database:
    handler: handler.database
    description: "Database GraphQL API."
    events:
      - http:
          path: db
          method: post
          cors: true
