#
# Copyright 2017 Alien Labs.
#

#
# Build artifacts (creates packaging).
# sls webpack
# ./webpack
#
# Deploy
# sls deploy
# ./serverless
# unzip -vl .serverless/web.zip
#

service: orbital-demo


provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1

  stage: dev

  environment:
    SERVICE_NAME: ${self:service}


plugins:
  # Custom domain name.
  # https://serverless.com/blog/serverless-api-gateway-domain
  # https://www.npmjs.com/package/serverless-domain-manager
  - "serverless-domain-manager"

  # Webpack
  # NOTE: Configures packaging (so package field in this config is ignored).
  # https://www.npmjs.com/package/serverless-webpack
  - "serverless-webpack"

  # sls offline start
  # http://localhost:3000
  - "serverless-offline"


custom:

  # https://console.aws.amazon.com/route53/home#DomainListing
  # https://serverless.com/blog/serverless-api-gateway-domain
  # sls create_domain Assigns cert to domain and configures CNAMES
  # TODO(burdon): https://github.com/amplify-education/serverless-domain-manager/issues/31 (burdon)
  # TODO(burdon): https://github.com/amplify-education/serverless-domain-manager/issues/32 (burdon)
  # TODO(burdon): https://console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=4512256671&language=en
  customDomain:
    domainName: www.orbitaldb.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true


# TODO(burdon): https://forum.serverless.com/t/use-wildcard-in-path-for-http-endpoints/2203 (wildcards)
# http://www.goingserverless.com/blog/routing-api-gateway-traffic-through-one-lambda-function
functions:
  site:
    handler: handler.site
    description: "Web Site."
    events:
      - http:
          path: favicon.ico
          method: get
      - http:
          path: static/{path}
          method: get
      - http:
          path: static/css/{path}
          method: get
      - http:
          path: /
          method: get
      - http:
          path: app
          method: get
      - http:
          path: debug
          method: get
      - http:
          path: login/{path}
          method: get
