#
# Copyright 2017 Alien Labs.
#

#
# Build artifacts (creates packaging).
# sls webpack
# ./webpack
#
# Deploy
# sls deploy
# ./serverless
# unzip -vl .serverless/web.zip
#

service: web

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1

  stage: dev

plugins:
  # Webpack
  # NOTE: Configures packaging (so package field in this config is ignored).
  # https://www.npmjs.com/package/serverless-webpack
  - "serverless-webpack"

  # Static assets
  # https://www.npmjs.com/package/serverless-finch
  # TODO(burdon): https://github.com/fernando-mc/serverless-finch/issues/4
  - "serverless-finch"

  # TODO(burdon): Custom domain name.
  # https://serverless.com/blog/serverless-api-gateway-domain
#  - "serverless-domain-manager"

  # TODO(burdon): Not used.
#  - "serverless-offline"

custom:
  client:
    # https://s3.amazonaws.com/orbital-web-assets
    bucketName: orbital-web-assets

  # TODO(burdon): Registered with AWS.
  # https://console.aws.amazon.com/route53/home#DomainListing
  # TODO(burdon): Configure CERT
  # https://serverless.com/blog/serverless-api-gateway-domain
#  customDomain:
#    domainName: orbitaldb.com
#    basePath: ''
#    stage: ${self:provider.stage}
#    createRoute53Record: true

# TODO(burdon): https://forum.serverless.com/t/use-wildcard-in-path-for-http-endpoints/2203 (wildcards)
# http://www.goingserverless.com/blog/routing-api-gateway-traffic-through-one-lambda-function
functions:
  site:
    handler: handler.site
    description: "Web Site."
    events:
      - http:
          path: favicon.ico
          method: get
      - http:
          path: static/{path}
          method: get
      - http:
          path: static/css/{path}
          method: get
      - http:
          path: /
          method: get
      - http:
          path: app
          method: get
      - http:
          path: debug
          method: get
