#
# Copyright 2017 Alien Labs.
#

#
# Build artifacts (creates packaging).
# sls webpack
# ./webpack
#
# Deploy
# sls client deploy
# ./serverless
# unzip -vl .serverless/web.zip
#

service: app

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1

  stage: dev

plugins:
  # Webpack
  # NOTE: Configures packaging (so package field in this config is ignored).
  # https://www.npmjs.com/package/serverless-webpack
  - "serverless-webpack"

  # Static assets
  # https://www.npmjs.com/package/serverless-finch
  # TODO(burdon): https://github.com/fernando-mc/serverless-finch/issues/4
  - "serverless-finch"

custom:
  client:
    # https://s3.amazonaws.com/orbital-web-assets
    bucketName: orbital-web-assets
