#
# Copyright 2017 Alien Labs.
#

#
# Console:
# https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions?display=list
#

# TODO(burdon): Serverless offline plugin.
# TODO(burdon): IAM roles for deploying lambda.

service: orbital

plugins:
  # Webpack
  # https://www.npmjs.com/package/serverless-webpack
  - "serverless-webpack"

  # sls info --json | jq
  # https://www.npmjs.com/package/serverless-plugin-info-json
  - "serverless-plugin-info-json"

custom:
  webpack: "webpack.config.js"

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1

  stage: dev

  environment:
    VERSION: "0.0.1"

functions:

  status:
    handler: handler.status
    description: "Status service."
    events:
      - http:
          path: status
          method: get

  registry:
    handler: handler.registry
    description: "Registry GraphQL API."
    events:
      - http:
          path: registry
          method: post

  database:
    handler: handler.database
    description: "Database GraphQL API."
    events:
      - http:
          path: db
          method: post
